package ocrequest

// The token is from sa image-pruner of namespace cluster-tasks
// This var is declared in config-clusters.go, which is generated by scripts/generate_config.sh
// config-clusters.go is not checked into git repo, because of tokens
// it must be fresh generated to compile the app by executing scripts/generate_config.sh
// var Clusters = T_ClusterConfig{
// 	Config: map[T_clName]T_Cluster{
// 		"dev-scp0": {"
// 			Name:          "dev-scp0",
// 			Url:           "https://api.dev-scp0.sf-rz.de:6443",
// 			Token:         "eyJh......",
// 			ConfigToolUrl: "https://scpconfig-service-master.apps.dev-scp0.sf-rz.de"},
// 		"cid-scp0": {"
// 			Name:          "cid-scp0",
// 			Url:           "https://api.cid-scp0.sf-rz.de:6443",
// 			Token:         "eyJh......",
// 			ConfigToolUrl: "https://scpconfig-service-master.apps.cid-scp0.sf-rz.de"},
// 		"ppr-scp0": {"
// 			Name:          "ppr-scp0",
// 			Url:           "https://api.ppr-scp0.sf-rz.de:6443",
// 			Token:         "eyJh......",
// 			ConfigToolUrl: "https://scpconfig-service-master.apps.ppr-scp0.sf-rz.de"},
// 		"vpt-scp0": {"
// 			Name:          "vpt-scp0",
// 			Url:           "https://api.vpt-scp0.sf-rz.de:6443",
// 			Token:         "eyJh......",
// 			ConfigToolUrl: "https://scpconfig-service-master.apps.vpt-scp0.sf-rz.de"},
// 		"pro-scp0": {"
// 			Name:          "pro-scp0",
// 			Url:           "https://api.pro-scp0.sf-rz.de:6443",
// 			Token:         "eyJh......",
// 			ConfigToolUrl: "https://scpconfig-service-master.apps.pro-scp0.sf-rz.de"},
// 	},
// }

var FamilyNamespaces T_famNsList
var AppNamespaces T_appNsList
var FamilyNamespacesStat = T_famNsList{
	"aps": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"aps-images", "aps-build"},
			"ppr-scp0": {"aps-images"},
			"vpt-scp0": {"aps-images"},
			"pro-scp0": {"aps-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"b2b": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"b2b-images"},
			"ppr-scp0": {"b2b-images"},
			"vpt-scp0": {"b2b-images"},
			"pro-scp0": {"b2b-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"b2c": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"b2c-images"},
			"ppr-scp0": {"b2c-images"},
			"vpt-scp0": {"b2c-images"},
			"pro-scp0": {"b2c-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"cbs": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"cbs-images"},
			"int-scp0": {"cbs-images"},
			"ppr-scp0": {"cbs-images"},
			"vpt-scp0": {"cbs-images"},
			"pro-scp0": {"cbs-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"dca": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"dca-images"},
			"int-scp0": {"dca-images"},
			"ppr-scp0": {"dca-images"},
			"vpt-scp0": {"dca-images"},
			"pro-scp0": {"dca-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"ebs": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"ebs-images", "ebs-build"},
			"ppr-scp0": {"ebs-images"},
			"vpt-scp0": {"ebs-images"},
			"pro-scp0": {"ebs-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"ibs": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"ibs-images"},
			"ppr-scp0": {"ibs-images"},
			"vpt-scp0": {"ibs-images"},
			"pro-scp0": {"ibs-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"pkp": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"pkp-images", "pkp-build"},
			"ppr-scp0": {"pkp-images"},
			"vpt-scp0": {"pkp-images"},
			"pro-scp0": {"pkp-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"scp": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"scp-images", "scp-build", "scp-baseimages"},
			"ppr-scp0": {"scp-images", "scp-baseimages"},
			"vpt-scp0": {"scp-images", "scp-baseimages"},
			"pro-scp0": {"scp-images", "scp-baseimages"},
		},
		Stages:      []T_clName{"dev-scp0", "cid-scp0", "ppr-scp0", "vpt-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"dev-scp0", "cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
	"vps": {
		ImageNamespaces: map[T_clName][]T_nsName{
			"cid-scp0": {"vps-images"},
			"ppr-scp0": {"vps-images"},
			"vpt-scp0": {"vps-images"},
			"pro-scp0": {"vps-images"},
		},
		Stages:      []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0", "pro-scp0"},
		Buildstages: []T_clName{"cid-scp0"},
		Teststages:  []T_clName{"cid-scp0", "ppr-scp0", "vpt-scp0"},
		Prodstages:  []T_clName{"pro-scp0"},
	},
}

var OcClient bool

var LogFileName = "image-tools.log"

var bitbucket_token = "NDk4MzkwOTAxNzgzOifliHsGrHWZUpubeoNMZbhM/7qT"
